spring:
  datasource:
    username: demouser
    password: demopassword
    url: "jdbc:postgresql://localhost:15432/postgres"
    driverClassName: org.postgresql.Driver
  flyway:
    user: demouser
    password: demopassword
    url: "jdbc:postgresql://localhost:15432/postgres"
    outOfOrder: true
  redis:
    port: 16379

  jpa:
    showSql: true
    properties:
      hibernate:
        format_sql=true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
