spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

    propertyNamingStrategy: SNAKE_CASE
    datasource:
    username: demouser
    password: demopassword
    url: "jdbc:postgresql://localhost:15432/postgres"
    driverClassName: org.postgresql.Driver
  flyway:
    user: demouser
    password: demopassword
    url: "jdbc:postgresql://localhost:15432/postgres"
    outOfOrder: true
  redis:
    port: 16379
    host: localhost
    database: 0
    timeout: 60000

  jpa:
    showSql: true
    properties:
      hibernate:
        format_sql=true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

application:
  urls:
    login: http://localhost:8081/login
    consent: http://localhost:8081/consent
    logout: http://localhost:8081/logout
    self:
      issuer: http://localhost:8080
